### ISSUE TITLE
Missing plus button for dc content link

### ISSUE THREAD

**Issue by lukeharrisontravis** [amplience/dc-extension-rich-text#17]
I went through the process of trying to include the option to add links to content items in my editor. The docs say to just add a contentTypes property which is an array of the content types. It says an icon should show up by default, but I don't see any icon or ability to add content items in my editor. 

![Screen Shot 2020-11-18 at 2 31 16 PM](https://user-images.githubusercontent.com/67061337/99596260-d59dcd80-29aa-11eb-9e4d-c0068ca71909.png)

As you can see, all of the icons are visible except one for dc-content-link.

Is this a bug? If not, can the docs be updated to describe the process of getting this working?

   "properties":{
      "textBox":{
         "type": "array",
         "ui:extension":{
            "url":"https://amplience.github.io/dc-extension-rich-text/index.html",
			"params": {
               "language": "json"
        	},
			"tools": {
                "whitelist": ["undo", "redo", "strong", "em", "code", "link", "lift", "bullet_list", "ordered_list", "image", "blockquote", "heading", "paragraph", "code_block", "horizontal_rule", "clear_formatting", "dc-image-link", "dc-content-link"],
				"dc-content-link": {
            		"contentTypes": ["https://demo.com/content/type/text-banner"]
        		}
    		}
         }
      }
   },

**Comment by PikinerLiliya** [comment]
Hi @lukeharrisontravis 
`tools` object should be inside `params` block.
