### ISSUE TITLE
Markdown rendering html tags

### ISSUE THREAD

**Issue by nbernardio** [amplience/dc-extension-rich-text#51]
Hi,

I'm using your extension on amplience but somehow got into an issue where it's rendering the html tags.

I have a title that is centered and a table
![image](https://user-images.githubusercontent.com/45160594/145053214-0ace8e08-eb4c-43d9-87d5-04be2788ba47.png)

![image](https://user-images.githubusercontent.com/45160594/145053320-22cc21cf-347a-4eb3-9de7-392acd46c472.png)

on the rendering template I have the following code
![image](https://user-images.githubusercontent.com/45160594/145053599-dec107fb-e0c6-4f54-b0af-ad34bfe90c84.png)

but when previewing the result, the table is rendering correctly but as you can see the **&lt;p&gt;** tag is displayed. So question is how do you render the html code along with the markdown correctly?

![image](https://user-images.githubusercontent.com/45160594/145054367-7267fc6d-4ad4-4720-b472-15d8425c1af2.png)

**Comment by asmith-lyonscg** [comment]
I've used this:
`{{{replace (replace (replace (markdown text.richtext) '&lt;' '<') '&gt;' '>') '&quot;' '"'}}}`
